import {
  FastifyInstance,
  FastifyReply,
  FastifyRequest,
} from "fastify";

import {
  authenticate,
  requirePermission,
  AuthClaims,
} from "../../auth/authorization";

import { writeAuditEvent } from "../../audit/audit";

import { PrismaClient } from "../../../../../packages/database/generated/prisma/client";

import {
  createCashBankTransaction,
} from "./cash-bank-service";

type TransactionBody = {
  organizationId?: unknown;
  bankAccountId?: unknown;
  voucherDate?: unknown;
  voucherNumber?: unknown;
  referenceNumber?: unknown;
  narration?: unknown;
  accountId?: unknown;
  amount?: unknown;
  lines?: unknown;
};

function error(
  reply: FastifyReply,
  statusCode: number,
  code: string,
  message: string,
) {
  return reply.code(statusCode).send({
    errors: [{ code, message }],
  });
}

function stringValue(
  value: unknown,
): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const result = value.trim();

  return result || undefined;
}

function dateValue(
  value: unknown,
): Date | undefined {
  if (
    typeof value !== "string" ||
    !/^\d{4}-\d{2}-\d{2}$/.test(value)
  ) {
    return undefined;
  }

  const date = new Date(
    `${value}T00:00:00.000Z`,
  );

  return Number.isNaN(date.getTime())
    ? undefined
    : date;
}

function numberValue(
  value: unknown,
): number | undefined {
  if (
    typeof value === "number" &&
    Number.isFinite(value)
  ) {
    return value;
  }

  if (
    typeof value === "string" &&
    value.trim()
  ) {
    const number = Number(value);

    if (Number.isFinite(number)) {
      return number;
    }
  }

  return undefined;
}

type RawLine = {
  accountId?: unknown;
  debit?: unknown;
  credit?: unknown;
  description?: unknown;
};

function normalizeLines(
  value: unknown,
): {
  accountId: string;
  debit: number;
  credit: number;
  description?: string;
}[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }

  const result = [];

  for (const item of value) {
    if (
      !item ||
      typeof item !== "object"
    ) {
      return undefined;
    }

    const line = item as RawLine;

    const accountId =
      stringValue(line.accountId);

    const debit =
      numberValue(line.debit ?? 0);

    const credit =
      numberValue(line.credit ?? 0);

    if (
      !accountId ||
      debit === undefined ||
      credit === undefined
    ) {
      return undefined;
    }

    if (debit < 0 || credit < 0) {
      return undefined;
    }

    if (debit > 0 && credit > 0) {
      return undefined;
    }

    result.push({
      accountId,
      debit,
      credit,
      description:
        stringValue(
          line.description,
        ),
    });
  }

  return result;
}

async function validateBankAccount(
  prisma: PrismaClient,
  tenantId: string,
  bankAccountId: string,
  organizationId: string,
  expectedType?: "BANK" | "CASH",
) {
  const account =
    await prisma.bankAccount.findFirst({
      where: {
        id: bankAccountId,
        tenantId,
        organizationId,
        active: true,
      },
      include: {
        glAccount: true,
      },
    });

  if (!account) {
    return {
      error:
        "Bank or cash account does not exist, is inactive, or belongs to another organization",
    };
  }

  if (
    expectedType &&
    account.accountType !== expectedType
  ) {
    return {
      error:
        `Account must be a ${expectedType} account`,
    };
  }

  return {
    account,
  };
}

export async function transactionRoutes(
  app: FastifyInstance,
  prisma: PrismaClient,
) {

  /*
   * =========================================================
   * BANKING TRANSACTION LIST
   *
   * Reads posted journal entries generated by banking
   * vouchers and returns the transaction lines relevant
   * to the selected bank/cash account.
   * =========================================================
   */
  app.get(
    "/api/banking/transactions",
    {
      preHandler: [
        authenticate,
        async (
          request: FastifyRequest,
          reply: FastifyReply,
        ) =>
          requirePermission(
            request,
            reply,
            "user.view",
          ),
      ],
    },
    async (request, reply) => {
      const claims = request.user as AuthClaims;

      const query = request.query as {
        bankAccountId?: unknown;
        fromDate?: unknown;
        toDate?: unknown;
        voucherType?: unknown;
        page?: unknown;
        pageSize?: unknown;
      };

      const bankAccountId =
        stringValue(query.bankAccountId);

      if (!bankAccountId) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "bankAccountId is required",
        );
      }

      const bankAccount =
        await prisma.bankAccount.findFirst({
          where: {
            id: bankAccountId,
            tenantId: claims.tenantId,
          },
          include: {
            organization: true,
            glAccount: true,
          },
        });

      if (!bankAccount) {
        return error(
          reply,
          404,
          "NOT_FOUND",
          "Bank or cash account not found",
        );
      }

      const parseQueryDate = (
        value: unknown,
      ): Date | undefined => {
        if (
          typeof value !== "string" ||
          !/^\d{4}-\d{2}-\d{2}$/.test(value)
        ) {
          return undefined;
        }

        const date = new Date(
          `${value}T00:00:00.000Z`,
        );

        return Number.isNaN(date.getTime())
          ? undefined
          : date;
      };

      const fromDate =
        query.fromDate === undefined
          ? undefined
          : parseQueryDate(query.fromDate);

      const toDate =
        query.toDate === undefined
          ? undefined
          : parseQueryDate(query.toDate);

      if (
        query.fromDate !== undefined &&
        !fromDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "fromDate must use YYYY-MM-DD format",
        );
      }

      if (
        query.toDate !== undefined &&
        !toDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "toDate must use YYYY-MM-DD format",
        );
      }

      if (
        fromDate &&
        toDate &&
        fromDate > toDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "fromDate cannot be after toDate",
        );
      }

      const pageRaw =
        typeof query.page === "string"
          ? Number(query.page)
          : 1;

      const pageSizeRaw =
        typeof query.pageSize === "string"
          ? Number(query.pageSize)
          : 50;

      const page =
        Number.isInteger(pageRaw) &&
        pageRaw > 0
          ? pageRaw
          : 1;

      const pageSize =
        Number.isInteger(pageSizeRaw) &&
        pageSizeRaw > 0 &&
        pageSizeRaw <= 200
          ? pageSizeRaw
          : 50;

      const voucherType =
        stringValue(
          query.voucherType,
        )?.toUpperCase();

      const allowedVoucherTypes = [
        "RECEIPT",
        "PAYMENT",
        "CONTRA",
      ];

      if (
        voucherType &&
        !allowedVoucherTypes.includes(
          voucherType,
        )
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "voucherType must be RECEIPT, PAYMENT or CONTRA",
        );
      }

      const where = {
        tenantId: claims.tenantId,
        status: "POSTED" as const,
        ...(fromDate || toDate
          ? {
              entryDate: {
                ...(fromDate
                  ? { gte: fromDate }
                  : {}),
                ...(toDate
                  ? {
                      lte: new Date(
                        toDate.getTime() +
                          24 *
                            60 *
                            60 *
                            1000 -
                          1,
                      ),
                    }
                  : {}),
              },
            }
          : {}),
        lines: {
          some: {
            accountId:
              bankAccount.glAccountId,
          },
        },
      };

      const [entries, totalCount] =
        await Promise.all([
          prisma.journalEntry.findMany({
            where,
            orderBy: [
              {
                entryDate: "desc",
              },
              {
                createdAt: "desc",
              },
            ],
            skip:
              (page - 1) * pageSize,
            take: pageSize,
            include: {
              organization: true,
              lines: {
                include: {
                  account: true,
                },
              },
            },
          }),
          prisma.journalEntry.count({
            where,
          }),
        ]);

      const data = entries
        .map((entry) => {
          const bankLine =
            entry.lines.find(
              (line) =>
                line.accountId ===
                bankAccount.glAccountId,
            );

          if (!bankLine) {
            return undefined;
          }

          const otherLines =
            entry.lines.filter(
              (line) =>
                line.accountId !==
                bankAccount.glAccountId,
            );

          let transactionType =
            "JOURNAL";

          if (
            entry.sourceType === "VOUCHER"
          ) {
            if (
              entry.entryNumber.startsWith(
                "RV-",
              )
            ) {
              transactionType =
                "RECEIPT";
            } else if (
              entry.entryNumber.startsWith(
                "PV-",
              )
            ) {
              transactionType =
                "PAYMENT";
            } else if (
              entry.entryNumber.startsWith(
                "CV-",
              )
            ) {
              transactionType =
                "CONTRA";
            }
          }

          if (
            voucherType &&
            transactionType !==
              voucherType
          ) {
            return undefined;
          }

          return {
            id: entry.id,
            entryNumber:
              entry.entryNumber,
            entryDate:
              entry.entryDate,
            description:
              entry.description,
            sourceType:
              entry.sourceType,
            sourceId:
              entry.sourceId,
            transactionType,
            bankAccountId,
            bankAccountCode:
              bankAccount.code,
            bankAccountName:
              bankAccount.name,
            debit:
              Number(bankLine.debit),
            credit:
              Number(bankLine.credit),
            amount:
              Number(bankLine.debit) -
              Number(bankLine.credit),
            counterAccounts:
              otherLines.map(
                (line) => ({
                  accountId:
                    line.accountId,
                  code:
                    line.account.code,
                  name:
                    line.account.name,
                  debit:
                    Number(line.debit),
                  credit:
                    Number(line.credit),
                  description:
                    line.description,
                }),
              ),
          };
        })
        .filter(
          (
            row,
          ): row is NonNullable<
            typeof row
          > => row !== undefined,
        );

      return {
        data,
        meta: {
          page,
          pageSize,
          totalCount,
          totalPages:
            Math.ceil(
              totalCount / pageSize,
            ),
        },
      };
    },
  );


  /*
   * =========================================================
   * RECEIPT
   *
   * Typical:
   *
   * Dr Bank/Cash
   * Cr Customer / Income / Other GL
   * =========================================================
   */
  app.post(
    "/api/banking/receipts",
    {
      preHandler: [
        authenticate,
        async (
          request: FastifyRequest,
          reply: FastifyReply,
        ) =>
          requirePermission(
            request,
            reply,
            "user.create",
          ),
      ],
    },
    async (request, reply) => {
      const claims =
        request.user as AuthClaims;

      const body =
        request.body as TransactionBody;

      const organizationId =
        stringValue(
          body.organizationId,
        );

      const bankAccountId =
        stringValue(
          body.bankAccountId,
        );

      const voucherDate =
        dateValue(body.voucherDate);

      if (
        !organizationId ||
        !bankAccountId ||
        !voucherDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "organizationId, bankAccountId and voucherDate are required",
        );
      }

      const bank =
        await validateBankAccount(
          prisma,
          claims.tenantId,
          bankAccountId,
          organizationId,
        );

      if (bank.error || !bank.account) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          bank.error ??
            "Bank or cash account could not be loaded",
        );
      }

      const amount =
        numberValue(body.amount);

      const accountId =
        stringValue(body.accountId);

      if (
        amount === undefined ||
        amount <= 0 ||
        !accountId
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "amount and accountId are required and amount must be greater than zero",
        );
      }

      const lines = [
        {
          accountId:
            bank.account.glAccountId,
          debit: amount,
          credit: 0,
          description:
            "Receipt - Bank/Cash",
        },
        {
          accountId,
          debit: 0,
          credit: amount,
          description:
            stringValue(body.narration),
        },
      ];

      try {
        const voucher =
          await createCashBankTransaction(
            prisma,
            {
              tenantId:
                claims.tenantId,
              organizationId,
              voucherTypeCode:
                "RECEIPT",
              voucherDate,
              voucherNumber:
                stringValue(
                  body.voucherNumber,
                ),
              referenceNumber:
                stringValue(
                  body.referenceNumber,
                ),
              narration:
                stringValue(
                  body.narration,
                ),
              lines,
            },
          );

        await writeAuditEvent(prisma, {
          tenantId:
            claims.tenantId,
          actorUserId:
            claims.sub,
          action: "CREATE",
          entityType: "ReceiptVoucher",
          entityId: voucher.id,
          requestId: request.id,
          newState: voucher,
        });

        return reply
          .code(201)
          .send({
            data: voucher,
          });
      } catch (err) {
        const message =
          err instanceof Error
            ? err.message
            : "Unable to create receipt";

        return error(
          reply,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? 409
            : 400,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? "CONFLICT"
            : "VALIDATION_ERROR",
          message,
        );
      }
    },
  );

  /*
   * =========================================================
   * PAYMENT
   *
   * Typical:
   *
   * Dr Supplier / Expense / Other GL
   * Cr Bank/Cash
   * =========================================================
   */
  app.post(
    "/api/banking/payments",
    {
      preHandler: [
        authenticate,
        async (
          request: FastifyRequest,
          reply: FastifyReply,
        ) =>
          requirePermission(
            request,
            reply,
            "user.create",
          ),
      ],
    },
    async (request, reply) => {
      const claims =
        request.user as AuthClaims;

      const body =
        request.body as TransactionBody;

      const organizationId =
        stringValue(
          body.organizationId,
        );

      const bankAccountId =
        stringValue(
          body.bankAccountId,
        );

      const voucherDate =
        dateValue(body.voucherDate);

      if (
        !organizationId ||
        !bankAccountId ||
        !voucherDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "organizationId, bankAccountId and voucherDate are required",
        );
      }

      const bank =
        await validateBankAccount(
          prisma,
          claims.tenantId,
          bankAccountId,
          organizationId,
        );

      if (bank.error || !bank.account) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          bank.error ??
            "Bank or cash account could not be loaded",
        );
      }

      const amount =
        numberValue(body.amount);

      const accountId =
        stringValue(body.accountId);

      if (
        amount === undefined ||
        amount <= 0 ||
        !accountId
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "amount and accountId are required and amount must be greater than zero",
        );
      }

      const lines = [
        {
          accountId,
          debit: amount,
          credit: 0,
          description:
            stringValue(body.narration),
        },
        {
          accountId:
            bank.account.glAccountId,
          debit: 0,
          credit: amount,
          description:
            "Payment - Bank/Cash",
        },
      ];

      try {
        const voucher =
          await createCashBankTransaction(
            prisma,
            {
              tenantId:
                claims.tenantId,
              organizationId,
              voucherTypeCode:
                "PAYMENT",
              voucherDate,
              voucherNumber:
                stringValue(
                  body.voucherNumber,
                ),
              referenceNumber:
                stringValue(
                  body.referenceNumber,
                ),
              narration:
                stringValue(
                  body.narration,
                ),
              lines,
            },
          );

        await writeAuditEvent(prisma, {
          tenantId:
            claims.tenantId,
          actorUserId:
            claims.sub,
          action: "CREATE",
          entityType: "PaymentVoucher",
          entityId: voucher.id,
          requestId: request.id,
          newState: voucher,
        });

        return reply
          .code(201)
          .send({
            data: voucher,
          });
      } catch (err) {
        const message =
          err instanceof Error
            ? err.message
            : "Unable to create payment";

        return error(
          reply,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? 409
            : 400,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? "CONFLICT"
            : "VALIDATION_ERROR",
          message,
        );
      }
    },
  );

  /*
   * =========================================================
   * CONTRA
   *
   * Bank/Cash to Bank/Cash.
   *
   * The request supplies the destination account.
   *
   * Example:
   *
   * Dr Bank B
   * Cr Bank A
   * =========================================================
   */
  app.post(
    "/api/banking/contra",
    {
      preHandler: [
        authenticate,
        async (
          request: FastifyRequest,
          reply: FastifyReply,
        ) =>
          requirePermission(
            request,
            reply,
            "user.create",
          ),
      ],
    },
    async (request, reply) => {
      const claims =
        request.user as AuthClaims;

      const body =
        request.body as TransactionBody;

      const organizationId =
        stringValue(
          body.organizationId,
        );

      const bankAccountId =
        stringValue(
          body.bankAccountId,
        );

      const destinationBankAccountId =
        stringValue(
          (body as TransactionBody & {
            destinationBankAccountId?: unknown;
          }).destinationBankAccountId,
        );

      const voucherDate =
        dateValue(body.voucherDate);

      if (
        !organizationId ||
        !bankAccountId ||
        !destinationBankAccountId ||
        !voucherDate
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "organizationId, bankAccountId, destinationBankAccountId and voucherDate are required",
        );
      }

      if (
        bankAccountId ===
        destinationBankAccountId
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "Source and destination accounts must be different",
        );
      }

      const source =
        await validateBankAccount(
          prisma,
          claims.tenantId,
          bankAccountId,
          organizationId,
        );

      if (source.error || !source.account) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          source.error ??
            "Source bank or cash account could not be loaded",
        );
      }

      const destination =
        await validateBankAccount(
          prisma,
          claims.tenantId,
          destinationBankAccountId,
          organizationId,
        );

      if (
        destination.error ||
        !destination.account
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          destination.error ??
            "Destination bank or cash account could not be loaded",
        );
      }

      const amount =
        numberValue(body.amount);

      if (
        amount === undefined ||
        amount <= 0
      ) {
        return error(
          reply,
          400,
          "VALIDATION_ERROR",
          "amount must be greater than zero",
        );
      }

      const lines = [
        {
          accountId:
            destination.account.glAccountId,
          debit: amount,
          credit: 0,
          description:
            "Contra - Destination",
        },
        {
          accountId:
            source.account.glAccountId,
          debit: 0,
          credit: amount,
          description:
            "Contra - Source",
        },
      ];

      try {
        const voucher =
          await createCashBankTransaction(
            prisma,
            {
              tenantId:
                claims.tenantId,
              organizationId,
              voucherTypeCode:
                "CONTRA",
              voucherDate,
              voucherNumber:
                stringValue(
                  body.voucherNumber,
                ),
              referenceNumber:
                stringValue(
                  body.referenceNumber,
                ),
              narration:
                stringValue(
                  body.narration,
                ),
              lines,
            },
          );

        await writeAuditEvent(prisma, {
          tenantId:
            claims.tenantId,
          actorUserId:
            claims.sub,
          action: "CREATE",
          entityType: "ContraVoucher",
          entityId: voucher.id,
          requestId: request.id,
          newState: voucher,
        });

        return reply
          .code(201)
          .send({
            data: voucher,
          });
      } catch (err) {
        const message =
          err instanceof Error
            ? err.message
            : "Unable to create contra voucher";

        return error(
          reply,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? 409
            : 400,
          message ===
            "DUPLICATE_VOUCHER_NUMBER"
            ? "CONFLICT"
            : "VALIDATION_ERROR",
          message,
        );
      }
    },
  );
}
